export enum CardColors {
  WOMAN_BLUE = 'BLUE',
  WOMAN_PURPLE = 'PURPLE',
  WOMAN_VIOLETTE = 'VIOLETTE',
  MAN_SKY_BLUE = 'SKY_BLUE',
  MAN_LIGHT_SKY_BLUE = 'LIGHT_SKY_BLUE',
  MAN_DEEP_SKY_BLUE = 'DEEP_SKY_BLUE',
}